on: [push]

jobs:
  publish:
    name: Publish to Cloudflare Pages

    runs-on: ubuntu-latest

    env:
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG }}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=langedge --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
